[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
priority=1

[program:hello]
command=gunicorn -k eventlet -b 127.0.0.1:5001 --chdir /app/apps hello:app
directory=/app/apps/hello
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/hello.err.log
stdout_logfile=/var/log/supervisor/hello.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:parking]
command=gunicorn -k eventlet -b 127.0.0.1:5002 --chdir /app/apps parking:app
directory=/app/apps/parking
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/parking.err.log
stdout_logfile=/var/log/supervisor/parking.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:nationofpositivity]
command=/strip-env.sh NATIONOFPOSITIVITY_ -- gunicorn -k eventlet -b 127.0.0.1:5004 --chdir /app/apps nationofpositivity.shop:server
directory=/app/apps/nationofpositivity
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nationofpositivity.err.log
stdout_logfile=/var/log/supervisor/nationofpositivity.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:homemadebycvg_com]
command=gunicorn -k eventlet -b 127.0.0.1:5005 --chdir /app/apps homemadebycvg:app
directory=/app/apps
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/homemadebycvg_com.err.log
stdout_logfile=/var/log/supervisor/homemadebycvg_com.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:getijden]
command=gunicorn -k eventlet -b 127.0.0.1:5006 --chdir /app/apps/getijden web:app
directory=/app/apps/getijden
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/getijden.err.log
stdout_logfile=/var/log/supervisor/getijden.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:letmelearn]
command=/strip-env.sh LETMELEARN_ -- gunicorn -k eventlet -b 127.0.0.1:5007 --chdir /app/apps/letmelearn letmelearn.web:server
directory=/app/apps/letmelearn
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/letmelearn.err.log
stdout_logfile=/var/log/supervisor/letmelearn.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:baseweb_demo]
command=/strip-env.sh BASEWEB_DEMO_ -- gunicorn -k eventlet -b 127.0.0.1:5008 --chdir /app/apps baseweb-demo:server
directory=/app/apps
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/baseweb_demo.err.log
stdout_logfile=/var/log/supervisor/baseweb_demo.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:howifeel]
command=/strip-env.sh HOWIFEEL_ -- gunicorn -k eventlet -b 127.0.0.1:5009 --chdir /app/apps/howifeel howifeel:app
directory=/app/apps/howifeel
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/howifeel.err.log
stdout_logfile=/var/log/supervisor/howifeel.out.log
environment=PYTHONUNBUFFERED="1"
priority=10

[program:oatk]
command=/strip-env.sh OATK_DEMO_ -- gunicorn -k eventlet -b 127.0.0.1:5010 --chdir /app/apps/oatk examples.google.app:server
directory=/app/apps/oatk
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/oatk.err.log
stdout_logfile=/var/log/supervisor/oatk.out.log
environment=PYTHONUNBUFFERED="1"
priority=10
